name: nitaloubryant
favicon: null
layout_spectrum: 0.51509
typography_spectrum: 0.4372
title: Calgary Singer-songwriter Nita Lou Bryant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2cec3'
    - '#f2f4ff'
    - '#9d9588'
    - '#420d5d'
    - '#936555'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
