name: nitaloubryant
favicon: null
layout_spectrum: 0.7983773876912892
typography_spectrum: 0.7941722897812724
title: Calgary Singer-songwriter Nita Lou Bryant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcb3a0'
    - '#b54e34'
    - '#455093'
    - '#b50000'
    - '#00826e'
  brandStrength: 0.905256713507697
  lightness: 0.74833066877909
  saturation: 0.486285200342536
  rhythmicContrast: 0.8766244682483375
purpose: []
