name: nitaloubryant
favicon: null
layout_spectrum: 0.7983773876912892
typography_spectrum: 1
title: Calgary Singer-songwriter Nita Lou Bryant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccc9bc'
    - '#bd9c00'
    - '#b2afa2'
    - '#1f1f48'
    - '#d1be32'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 1
purpose: []
